# Generated by Django 4.1.4 on 2023-01-23 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_category_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sales',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
