# Generated by Django 4.1.4 on 2023-01-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_products_created_at_sales_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='created_at',
            new_name='s_created_at',
        ),
    ]
