# Generated by Django 4.1.4 on 2023-01-24 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_created_at_sales_s_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='s_created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
