# Generated by Django 4.0.8 on 2023-01-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_adminlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adminlogin',
        ),
    ]
